AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CodeBuild project with passphrase (Educational Purposes Only)

Parameters:
  Passphrase:
    Type: String
    NoEcho: true
    Description: The passphrase for the build process.

Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: '/'
      Policies:
        - PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:*'

  SampleCodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: ExampleCodeBuildProject
      Description: 'An example CodeBuild project that uses a passphrase.'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: PASSPHRASE
            Value: "PASSPHRASEabcedfg!!12"
            Type: PLAINTEXT
          - Name:  password
            Value:  "password"
            Type:  PLAINTEXT
      Source:
        Type: CODECOMMIT
        Location: 'https://example.com/aws/some-code-repository.git'
      TimeoutInMinutes: 60