import boto3

def lambda_handler(event, context):
    ec2 = boto3.client('ec2')

    # Getting instances with the specific tag
    instances = ec2.describe_instances(
        Filters=[
            {'Name': 'tag:platform', 'Values': ['lab']}
        ]
    )

    instance_ids = []
    for reservation in instances['Reservations']:
        for instance in reservation['Instances']:
            instance_ids.append(instance['InstanceId'])

    if not instance_ids:
        print("No instances with the specified tag found.")
        return

    # Check the operation to perform
    if event.get('operation') == 'start':
        # Starting instances
        ec2.start_instances(InstanceIds=instance_ids)
        print(f"Started instances: {instance_ids}")
    elif event.get('operation') == 'stop':
        # Stopping instances
        ec2.stop_instances(InstanceIds=instance_ids)
        print(f"Stopped instances: {instance_ids}")
    else:
        print("Invalid operation specified. Use 'start' or 'stop'.")

# Sample event format to use with this Lambda function:
# event = {'operation': 'start'}  # or 'stop'
# generated by ai