AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Description: Project Name (like workshop, immersionday, awsjams)
    Type: String
    Default: ambassador
  Environment:
    Description: Environment
    Type: String
    Default:  lab
  Author:
    Description: Author 
    Type: String
    Default: rdevera@tenable.com
  Version:
    Description: Version
    Type: String
    Default: v1
    
Resources:
  # IAM Policy for Read-Only Access
  ReadOnlyPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'ReadOnlyAccessPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Resource: '*'
          - Effect: 'Allow'
            Action: 's3:Get*'
            Resource: '*'
      Users:
        - !Ref OHcnappUser001
        - !Ref OHcnappUser002
        - !Ref OHcnappUser003
        - !Ref OHcnappUser004
        - !Ref OHcnappUser005
        - !Ref OHcnappUser006
        - !Ref OHcnappUser007
        - !Ref OHcnappUser008
        - !Ref OHcnappUser009
        - !Ref OHcnappUser010
        - !Ref OHcnappUser011
        - !Ref OHcnappUser012
        - !Ref OHcnappUser013
        - !Ref OHcnappUser014
        - !Ref OHcnappUser015
        - !Ref OHcnappUser016
        - !Ref OHcnappUser017
        - !Ref OHcnappUser018
        - !Ref OHcnappUser019
        - !Ref OHcnappUser020

  # IAM Users 001 to 020
  OHcnappUser001:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser001'
      # No access keys, no console access

  OHcnappUser002:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser002'

  OHcnappUser003:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser003'

  OHcnappUser004:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser004'

  OHcnappUser005:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser005'

  OHcnappUser006:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser006'

  OHcnappUser007:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser007'

  OHcnappUser008:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser008'

  OHcnappUser009:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser009'

  OHcnappUser010:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser010'

  OHcnappUser011:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser011'

  OHcnappUser012:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser012'

  OHcnappUser013:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser013'

  OHcnappUser014:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser014'

  OHcnappUser015:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser015'

  OHcnappUser016:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser016'

  OHcnappUser017:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser017'

  OHcnappUser018:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser018'

  OHcnappUser019:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser019'

  OHcnappUser020:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'OHcnappUser020'
