AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create two users with deny access and generate access keys.  Used to demonstrate storing secrets.

Resources:
  OHcnappDenyAdminGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'DenyAdministratorsGroup'

  AdminPolicyAttachment:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'DenyAdministratorAccessPolicy'
      Groups:
        - !Ref OHcnappDenyAdminGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: '*'
            Resource: '*'

  OHcnappNoGoat01:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'nogoat01'
      Policies: []

  OHcnappNoGoat02:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'nogoat02'
      Policies: []

  OHcnappSecretNoGoatToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref OHcnappDenyAdminGroup
      Users:
        - !Ref OHcnappNoGoat01

  NoGoatToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref OHcnappDenyAdminGroup
      Users:
        - !Ref OHcnappNoGoat02

  AccessKeyForNoGoat01:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref OHcnappNoGoat01

  AccessKeyForNoGoat02:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref OHcnappNoGoat02

Outputs:
  NoGoat01UserArn:
    Description: 'ARN for NoGoat01'
    Value: !GetAtt OHcnappNoGoat01.Arn
  NoGoat01AccessKeyId:
    Description: 'Access Key ID for SecretGoat'
    Value: "AAIAYA6A3ADAWEXAMPLE"
#    Value: !Ref AccessKeyForNoGoat01
  NoGoat01SecretAccessKey:
    Description: 'Secret Access Key for SecretGoat'
    Value: "7AnAGALAxAYAgABA9AzAAAUA5AcEXAMPLESECRET"
#    Value: !GetAtt AccessKeyForNoGoat01.SecretAccessKey

  NoGoat02UserArn:
    Description: 'ARN for NoGoat02'
    Value: !GetAtt OHcnappNoGoat02.Arn
  NoGoat02AccessKeyId:
    Description: 'Access Key ID for labgoat'
    Value: "AAIAYA6A3ADAWEXAMPLE"
#    Value: !Ref AccessKeyForNoGoat02
  NoGoat02SecretAccessKey:
    Description: 'Secret Access Key for labgoat'
    Value: "7AnAGALAxAYAgABA9AzAAAUA5AcEXAMPLESECRET"
#    Value: !GetAtt AccessKeyForNoGoat02.SecretAccessKey
