AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an S3 bucket with a KMS key having no automatic rotation.

Parameters:
  ProjectName:
    Description: Project Name (like workshop, immersionday, awsjams)
    Type: String
    Default: ambassador
  Environment:
    Description: Environment
    Type: String
    Default:  lab
  Author:
    Description: Author 
    Type: String
    Default: rdevera@tenable.com
  Version:
    Description: Version
    Type: String
    Default: v1


Resources:
  OHcnappKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for encrypting S3 bucket data without automatic key rotation
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
      EnableKeyRotation: false # No key rotation

  OHcnappS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  !Sub 'ohcnapp-${AWS::StackName}-${AWS::Region}-bucket'
#      BucketName: ohcnapp-secure-bucket 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref OHcnappKMSKey # Use the KMS key without rotation
      VersioningConfiguration:
        Status: Enabled 

Outputs:
  OHcnappBucketName:
    Description: The name of the S3 bucket with KMS encryption
    Value: !Ref OHcnappS3Bucket