AWSTemplateFormatVersion: '2010-09-09'
Resources:
  OHcnappQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OHcnappQueue

  OHcnappLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          def lambda_handler(event, context):
          #####
          # placeholder for code
          ####
          
          return {
            'statusCode': 200,
            'body': 'Webhook received'
          }
      Runtime: python3.8

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaSQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sqs:SendMessage"
                Resource: !GetAtt OHcnappQueue.Arn

  OHcnappApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OHcnappApi

  OHcnappResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt OHcnappApi.RootResourceId
      PathPart: 'webhook'
      RestApiId: !Ref OHcnappApi

  OHcnappMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref OHcnappResource
      RestApiId: !Ref OHcnappApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OHcnappLambda.Arn}/invocations
