AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating a role and attaching policies
Parameters:
  ProjectName:
    Description: Project Name (like workshop, immersionday, awsjams)
    Type: String
    Default: ambassador
  Environment:
    Description: Environment
    Type: String
    Default:  lab
  Author:
    Description: Author 
    Type: String
    Default: rdevera@tenable.com
  Version:
    Description: Version
    Type: String
    Default: v1
    
Resources:
  OHcnappRole001:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "OHcnappRole001"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      
  OHcnappNewPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # First version allowing some actions
          - Effect: 'Allow'
            Action:
              - "*"
            Resource:
              - "*"
      ManagedPolicyName: "OHcnappNewPolicy"
  OHcnappPolicyVersion:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'MyManagedPolicyWithVersion'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Second version that denies some actions
          - Effect: 'Deny'
            Action:
              - 's3:DeleteObject'
            Resource:
              - 'arn:aws:s3:::example-bucket/*'
      Roles:
        - !Ref 'OHcnappRole001'
