AWSTemplateFormatVersion: 2010-09-09
Description: Oh CNAPP S3 Demo Template
Parameters:
  ProjectName:
    Description: Project Name (like workshop, immersionday, awsjams)
    Type: String
    Default: ambassador
  Environment:
    Description: Environment
    Type: String
    Default:  lab
  Author:
    Description: Author (should be meta data)
    Type: String
    Default: rdevera@tenable.com
  Version:
    Description: Version
    Type: String
    Default: v1
  
Resources:

  OHcnappS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ohcnapp-${AWS::StackName}-${AWS::Region}-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
           - Key: "platform"
             Value: "Lab"
           - Key: "access"
             Value: "demo"

  OHcnappPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OHcnappS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
            - Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource:  
                - !Sub "arn:aws:s3:::${OHcnappS3Bucket}/*"
      
Outputs:
  BucketName:
    Description: Name of the S3 Bucket
    Value: !Ref OHcnappS3Bucket




